---
- name: Deploy Calculator App
  hosts: servers
  become: yes

  tasks:

      - name: Pull latest Docker image
        docker_image:
            name: kautilyasingh/calculator-app
            tag: latest
            source: pull

      - name: Run calculator container
        docker_container:
            name: calculator-app
            image: kautilyasingh/calculator-app:latest
            state: started
            recreate: yes
            tty: true
            stdin_open: true
            ports:
              - "8081:8080"
